/**
 * @file    board2_it.c
 * @brief   Board 2 interrupt callback routing
 *
 * @details This file provides the HAL_GPIO_EXTI_Callback that dispatches
 *          to the encoder (PA5) and limit switch (PA8) handlers.
 *
 *          Add to your CubeMX project alongside board2.c.
 *          The HAL_TIM_PeriodElapsedCallback for steppers goes in main.c
 *          or stm32f4xx_it.c as with Board 1.
 *
 *          EXTI9_5_IRQHandler is generated by CubeMX in stm32f4xx_it.c
 *          and calls HAL_GPIO_EXTI_IRQHandler, which clears the pending
 *          bit and calls this callback.
 */

#include "stm32f4xx_hal.h"
#include "encoder.h"
#include "limits.h"
#include "pins.h"

/**
 * @brief  HAL GPIO EXTI callback — routes by pin.
 *
 *         If you have other EXTI pins, add them here.
 *         This overrides the __weak version in stm32f4xx_hal_gpio.c.
 */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    if (GPIO_Pin == ENC_CLK_PIN) {       /* PA5 — encoder */
        encoder_exti_handler();
    }
    else if (GPIO_Pin == DRUM_LIM_PIN) { /* PA8 — limit switch */
        limits_exti_handler();
    }
}
